Develop
VKGL-Kwaliteit/BioinformaticaVeldnorm pull request #2
Opened 2023-06-30 09:51 UTC by Bratdaking

Hey all,

Added the development procedure, with a recommendation and howto for the use of git flow.

Kind regards,
Bart de Koning [MUMC]

2023-08-17 15:03 UTC, rernst requested changes

2023-08-17 15:03 UTC, rernst commented on README.md
> +request on VKGL-Kwaliteit:main.
I think everyone should work on a feature branch and pull updates to develop. We then can create a release (timing to be determined) by merging develop with main.

2023-08-17 15:03 UTC, rernst commented on README.md
> +request on VKGL-Kwaliteit:main.
If you work on a fork you can push directly to develop as well.

2023-09-22 12:00 UTC, closed without merging

2023-09-22 12:01 UTC, Bratdaking commented
This pull request is closed in favour of pull request #9 which will be in line with the proposed procedure.